#!/bin/bash

# this script aims to make a JS array syntaxed string containing
# the paths of the files generated by next on build time bc we'll
# need them to pre-caching these files with workbox

# putting quotes ensures that the newlines are not wiped by 
# the command substitution
files="$(cd ./out && find _next | grep -E "\.(js|css)$")"

# open the array
outputdata="["

# gets each line in files w/out processing the backslash stuff
while read -r line; 
  # prevents newline-only lines to be treated
  do if [[ -n "$line" ]]; then outputdata+="\"${line}\","; fi
done < <(echo "$files") # process substitution to mock a FD

# removes the last comma if the array contains data
if [[ -n "$files" ]]; then outputdata="${outputdata::-1}"; fi
# close the array
outputdata+="]"

# put the array inside a file
echo $outputdata > ./out/assets/chunk-paths.txt